// AUTO-GENERATED by scripts/sync-paintings.mjs
// Edit data/paintings.yaml, then re-run: pnpm sync-paintings

export interface Painting {
  id: string;
  title: string;
  filename: string;
  year?: number;
  series?: string;
  dimensions?: string;
  medium?: string;
}

const paintings: Painting[] = [
  { id: "e1bf9032", title: "The Bund, Shanghai", filename: "the-bund-shanghai.jpg" },
  { id: "6ef479cb", title: "Clematis", filename: "clematis.jpg" },
  { id: "a0cbc0de", title: "Delft Market Square", filename: "delft-square.jpg", series: "Dutch Townscapes" },
  { id: "d48c4bf7", title: "German Trade House", filename: "german-trade-house.jpg" },
  { id: "6e981b3f", title: "Harbour View, Dordrecht", filename: "harbour-view-dordrecht.jpg", series: "Dutch Townscapes" },
  { id: "bdfba010", title: "Havana Street", filename: "havana-street.jpg" },
  { id: "00bdc875", title: "Onsala House", filename: "onsala-house.jpg" },
  { id: "751ed854", title: "Kungsbacka Creek", filename: "kungsbacka-creek.jpg" },
  { id: "b08cdb50", title: "Lisbon Street", filename: "lisbon-street.jpg" },
  { id: "20359412", title: "Noon in Querétaro", filename: "queretaro-noon.jpg" },
  { id: "97553a47", title: "Piazza in Faro, Portugal", filename: "piazza-faro.jpg" },
  { id: "b70f955f", title: "Vrångö Island, Sweden", filename: "vragno-island.jpg" },
];

export default paintings;
