// AUTO-GENERATED by scripts/sync-paintings.mjs
// Edit titles and years in data/paintings-meta.json, then re-run sync.

export interface Painting {
  id: string;
  title: string;
  filename: string;
  year?: number;
}

const paintings: Painting[] = [
  { id: "1531a31f", title: "Lisbon Tram", filename: "lisbon-tram.jpg" },
  { id: "1067d297", title: "Vrangö Harbor", filename: "vrangö-harbor.jpg" },
];

export default paintings;
