// AUTO-GENERATED by scripts/sync-paintings.mjs
// Edit titles, years, dimensions, and series in data/paintings-meta.json, then re-run sync.

export interface Painting {
  id: string;
  title: string;
  filename: string;
  year?: number;
  dimensions?: string;
  series?: string;
}

const paintings: Painting[] = [
  { id: "2403d79b", title: "20231007 170233", filename: "20231007-170233.jpg" },
  { id: "f0b00329", title: "20231007 170347", filename: "20231007-170347.jpg" },
  { id: "a0ae384b", title: "20231007 171004", filename: "20231007-171004.jpg" },
  { id: "8f1a76d8", title: "20231007 171220", filename: "20231007-171220.jpg" },
  { id: "ef6b6de2", title: "20250403 155920", filename: "20250403-155920.jpg" },
  { id: "fe49cb04", title: "20250403 155956", filename: "20250403-155956.jpg" },
  { id: "44e0c78e", title: "20250403 162251", filename: "20250403-162251.jpg" },
  { id: "38823844", title: "Behind The Sint Janskerk, Gouda", filename: "behind-the-sint-janskerk-gouda.jpg", series: "Netherlands" },
  { id: "183832dd", title: "Cavacos, Portugal", filename: "cavacos-portugal.jpg", series: "Portugal" },
  { id: "e85cf3b6", title: "Clematis I", filename: "clematis-1.jpg", series: "Flowers" },
  { id: "428aede7", title: "Clematis II", filename: "clematis-2.jpg", series: "Flowers" },
  { id: "c87f5189", title: "Clematis III", filename: "clematis-3.jpg", series: "Flowers" },
  { id: "33f0f0a2", title: "Clematis IV", filename: "clematis-4.jpg", series: "Flowers" },
  { id: "79bce3db", title: "Delft Bridges I", filename: "delft-bridges-1.jpg", series: "Netherlands" },
  { id: "cf3f99ea", title: "Delft Bridges II", filename: "delft-bridges-2.jpg", series: "Netherlands" },
  { id: "9d35cd82", title: "Delft Bridges III", filename: "delft-bridges-3.jpg", series: "Netherlands" },
  { id: "69c583ad", title: "Delft Bridges IV", filename: "delft-bridges-4.jpg", series: "Netherlands" },
  { id: "a0cbc0de", title: "Delft Square", filename: "delft-square.jpg", series: "Netherlands" },
  { id: "2c957fb9", title: "Field in the Rain", filename: "field-in-the-rain.jpg", series: "Landscape" },
  { id: "13bd1c4c", title: "Gottskär Marina", filename: "gottskar-marina.jpg", series: "Sweden" },
  { id: "33f231d6", title: "Harbour View I", filename: "harbour-view-1.jpg" },
  { id: "40ae4664", title: "Harbour View II", filename: "harbour-view-2.jpg" },
  { id: "b698b9aa", title: "Havana Street", filename: "havana-street-01.jpg", series: "Cuba" },
  { id: "3ceb2f56", title: "Hillside Spring", filename: "hillside-spring.jpg", series: "Landscape" },
  { id: "c8d6594b", title: "Hillside Winter", filename: "hillside-winter.jpg", series: "Landscape" },
  { id: "7372f10f", title: "Kungsbacka Creek I", filename: "kungsbacka-creek-01.jpg", series: "Sweden" },
  { id: "d871c5d8", title: "Kungsbacka Creek II", filename: "kungsbacka-creek-02.jpg", series: "Sweden" },
  { id: "48fa6ff3", title: "Kungsbacka Creek", filename: "kungsbacka-creek-sweden.jpg", series: "Sweden" },
  { id: "356e70bb", title: "Kungsbackan Sketch", filename: "kungsbackan-sketch.jpg", series: "Sweden" },
  { id: "88058acd", title: "Kungsbackan", filename: "kungsbackan.jpg", series: "Sweden" },
  { id: "90bb1219", title: "Lisboa I", filename: "lisboa-01.jpg", series: "Portugal" },
  { id: "4586396a", title: "Lisboa II", filename: "lisboa-02.jpg", series: "Portugal" },
  { id: "83041895", title: "Misty Woods", filename: "misty-woods.jpg", series: "Landscape" },
  { id: "a3be361c", title: "Noon Time in Querétaro", filename: "noon-time-in-qeretaro-mexico.jpg", series: "Mexico" },
  { id: "d31cc505", title: "Old Harbour I", filename: "old-harbour-1.jpg" },
  { id: "f986d53e", title: "Old Harbour II", filename: "old-harbour-2.jpg" },
  { id: "4fa839fe", title: "Old Harbour III", filename: "old-harbour-3.jpg" },
  { id: "8694d3b0", title: "Onsala Fjorden", filename: "onsala-fjorden.jpg", series: "Sweden" },
  { id: "f359ad07", title: "Onsala Marina", filename: "onsala-marina-01.jpg", series: "Sweden" },
  { id: "183da572", title: "Piazza in Faro", filename: "piazza-in-faro-portugal.jpg", series: "Portugal" },
  { id: "e127e0b7", title: "Querétaro Noon", filename: "queretaro-noon-01.jpg", series: "Mexico" },
  { id: "0dcca1ab", title: "Sketches", filename: "sketchs-1.jpg" },
  { id: "7b850b27", title: "Village View", filename: "village-view.jpg", series: "Landscape" },
  { id: "e9949d62", title: "Vrångö Island", filename: "vragno-island-sweden.jpg", series: "Sweden" },
  { id: "a81ee763", title: "Vrångö Island, 2019", filename: "vrango-island-sweden-2019.jpg", series: "Sweden" },
  { id: "2fd6308d", title: "Winter Field", filename: "winter-field.jpg", series: "Landscape" },
  { id: "678cbb0f", title: "Woods", filename: "woods.jpg", series: "Landscape" },
];

export default paintings;
